function env-sync --description "Sync API keys from Bitwarden to environment"
    # Parse arguments
    set -l force_overwrite false
    for arg in $argv
        switch $arg
            case --force -f
                set force_overwrite true
            case --help -h
                echo "Sync API keys from Bitwarden to environment"
                echo ""
                echo "Usage: env-sync [options]"
                echo ""
                echo "Options:"
                echo "  -f, --force    Force refresh all variables (even unchanged)"
                echo "  -h, --help     Show this help message"
                echo ""
                echo "Behavior:"
                echo "  - New variables: Always set"
                echo "  - Changed values: Auto-updated (smart sync)"
                echo "  - Unchanged values: Skipped"
                echo "  - All values persisted to ~/.config/fish/conf.d/env-sync-vars.fish"
                return 0
        end
    end

    # Source CachyOS config
    source /usr/share/cachyos-fish-config/cachyos-config.fish

    # Unlock Bitwarden and get session (prompt for password if needed)
    # Skip if already unlocked
    if not set -q BW_SESSION
        or test -z "$BW_SESSION"
        echo (set_color -o ff9900)"Unlocking Bitwarden"(set_color normal)
        set -gx BW_SESSION (bw unlock --raw)
    end

    # Get the field names first
    set -l field_names (bw get item "API Keys" --session "$BW_SESSION" | jq -r '.fields[].name')

    # Print what we're syncing
    echo "Syncing environment variables from Bitwarden:"
    for key in $field_names
        echo "  - $key"
    end

    # Ensure the persistent config directory exists
    set -l persist_dir "$HOME/.config/fish/conf.d"
    set -l persist_file "$persist_dir/env-sync-vars.fish"
    
    if not test -d $persist_dir
        mkdir -p $persist_dir
    end

    # Clear the persistent file (we'll rewrite it)
    echo "# Auto-generated by env-sync - do not edit manually" > $persist_file
    echo "# Synced on "(date) >> $persist_file

    # Export each custom field as an environment variable
    # Using 'bw get item' with the session to avoid re-authentication
    bw get item "API Keys" --session "$BW_SESSION" | jq -r '.fields[] | "\(.name)=\(.value)"' | while read -l line
        set -l var_name (echo $line | cut -d'=' -f1)
        set -l var_value (echo $line | cut -d'=' -f2-)
        
        # Check if variable already exists and if value matches
        set -l exists false
        set -l current_value ""
        set -l needs_update false
        
        if set -q $var_name
            set exists true
            set current_value $$var_name
            if test "$current_value" != "$var_value"
                set needs_update true
            end
        end
        
        # Set in current session if: doesn't exist, value differs, or --force
        if test "$exists" = "false"
            # New variable
            set -gx $var_name $var_value
            echo "  Set: $var_name"
        else if test "$needs_update" = "true"
            # Value differs from Bitwarden - smart update
            set -gx $var_name $var_value
            echo "  Updated (value changed): $var_name"
        else if test "$force_overwrite" = "true"
            # Same value but --force was used
            set -gx $var_name $var_value
            echo "  Refreshed: $var_name"
        else
            # Same value, no --force, skip
            echo "  Skipped (unchanged): $var_name"
        end
        
        # Always persist to file (for next shell startup)
        echo "set -gx $var_name $var_value" >> $persist_file
    end

    echo "Variables persisted to: $persist_file"

    # Lock the vault after syncing
    bw lock --session "$BW_SESSION"

    # Clean up the session variable
    set -e BW_SESSION

    echo "Environment sync complete!"
end
