function env-sync --description "Sync API keys from Bitwarden to environment"
    # Parse arguments
    set -l force_overwrite false
    for arg in $argv
        switch $arg
            case --force -f
                set force_overwrite true
            case --help -h
                echo "Usage: env-sync [options]"
                echo "Options:"
                echo "  -f, --force    Overwrite existing environment variables"
                echo "  -h, --help     Show this help message"
                return 0
        end
    end

    # Source CachyOS config
    source /usr/share/cachyos-fish-config/cachyos-config.fish

    # Unlock Bitwarden and get session (prompt for password if needed)
    # Skip if already unlocked
    if not set -q BW_SESSION
        or test -z "$BW_SESSION"
        echo (set_color -o ff9900)"Unlocking Bitwarden"(set_color normal)
        set -gx BW_SESSION (bw unlock --raw)
    end

    # Get the field names first
    set -l field_names (bw get item "API Keys" --session "$BW_SESSION" | jq -r '.fields[].name')

    # Print what we're syncing
    echo "Syncing environment variables from Bitwarden:"
    for key in $field_names
        echo "  - $key"
    end

    # Ensure the persistent config directory exists
    set -l persist_dir "$HOME/.config/fish/conf.d"
    set -l persist_file "$persist_dir/env-sync-vars.fish"
    
    if not test -d $persist_dir
        mkdir -p $persist_dir
    end

    # Clear the persistent file (we'll rewrite it)
    echo "# Auto-generated by env-sync - do not edit manually" > $persist_file
    echo "# Synced on "(date) >> $persist_file

    # Export each custom field as an environment variable
    # Using 'bw get item' with the session to avoid re-authentication
    bw get item "API Keys" --session "$BW_SESSION" | jq -r '.fields[] | "\(.name)=\(.value)"' | while read -l line
        set -l var_name (echo $line | cut -d'=' -f1)
        set -l var_value (echo $line | cut -d'=' -f2-)
        
        # Check if variable already exists in current session
        set -l exists false
        if set -q $var_name
            set exists true
        end
        
        # Only set in current session if --force or doesn't exist
        if test "$force_overwrite" = "true"; or test "$exists" = "false"
            # Set in current session
            set -gx $var_name $var_value
            if test "$exists" = "true" -a "$force_overwrite" = "true"
                echo "  Overwritten: $var_name"
            else if test "$exists" = "false"
                echo "  Set: $var_name"
            end
        else
            echo "  Skipped (already exists): $var_name"
        end
        
        # Always persist to file (for next shell startup)
        echo "set -gx $var_name $var_value" >> $persist_file
    end

    echo "Variables persisted to: $persist_file"

    # Lock the vault after syncing
    bw lock --session "$BW_SESSION"

    # Clean up the session variable
    set -e BW_SESSION

    echo "Environment sync complete!"
end
